// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Sd16pXzs6Y0OmQf4sQbXXCyK0Rf2oZ8',
    appId: '1:536402173673:web:78a6eab342effaadaf1a78',
    messagingSenderId: '536402173673',
    projectId: 'flash-chat-fe5f8',
    authDomain: 'flash-chat-fe5f8.firebaseapp.com',
    storageBucket: 'flash-chat-fe5f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnH5Zh1UOiFiRdgdIwip8JbYNK1p0kJNk',
    appId: '1:536402173673:android:6d4c86fd5cc1bb5eaf1a78',
    messagingSenderId: '536402173673',
    projectId: 'flash-chat-fe5f8',
    storageBucket: 'flash-chat-fe5f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtLcrMyH5UAylaOYroey_wBBGSW6yJpZU',
    appId: '1:536402173673:ios:228ec72704843906af1a78',
    messagingSenderId: '536402173673',
    projectId: 'flash-chat-fe5f8',
    storageBucket: 'flash-chat-fe5f8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtLcrMyH5UAylaOYroey_wBBGSW6yJpZU',
    appId: '1:536402173673:ios:228ec72704843906af1a78',
    messagingSenderId: '536402173673',
    projectId: 'flash-chat-fe5f8',
    storageBucket: 'flash-chat-fe5f8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4Sd16pXzs6Y0OmQf4sQbXXCyK0Rf2oZ8',
    appId: '1:536402173673:web:54159dee23acc8f8af1a78',
    messagingSenderId: '536402173673',
    projectId: 'flash-chat-fe5f8',
    authDomain: 'flash-chat-fe5f8.firebaseapp.com',
    storageBucket: 'flash-chat-fe5f8.appspot.com',
  );
}
